### ISSUE TITLE
Unable to use GPU

### ISSUE THREAD

**Issue by ket0x4** [BananoCoin/boompow#1]
It says:
```
🚀 Initiating connection to BoomPOW...
⚠️ Unable to use GPU Build program failure
⚠️ Unable to initialize any GPUs, using CPU2022/08/14 15:46:43 Dial: connection was successfully established with wss://boompow.banano.cc/ws/worker
```

GPU: Vega 3 Mobile. AMDGPU: 22.0.0-1.fc36, MESA: 22.1.6-1.fc36
CPU: Ryzen 3 2200U (x86_64)
OS: Fedora 36 (Silverblue)

**Comment by bbedward** [comment]
Can you add more info:

- Your platform+architecture
- Your GPU and driver version

**Comment by ket0x4** [comment]
> Can you add more info:
> 
> * Your platform+architecture
> * Your GPU and driver version

Sorry I forgot. Now added

**Comment by bbedward** [comment]
I'm thinking you need OpenCL which is only in the pro driver, I think following the steps here should resolve it

https://blog.onlyesterday.net/post/tech/2022_06_14_amd_hip_opencl/#gsc.tab=0

**Comment by ket0x4** [comment]
Thank you but I use silverblue. I don't think it's possible to use amdgpu-pro on silverblue 🥲

**Comment by bbedward** [comment]
It's possible, this is technically not installing the entire driver only the OpenCL part.

The amdgpu pro just gives you a script, you might just have to modify the script to not error out on silverblue (I did something similar for popos).

I'd follow the steps, if it fails at `amdgpu-install` with an error like silverblue is not supported you can just edit the script.

```
which amdgpu-install
sudo nano /path/to/script
```
