### ISSUE TITLE
bad handshake

### ISSUE THREAD

**Issue by AquilesCrespo** [BananoCoin/boompow#2]
I have today experimented and I am experiencing the following: (am I missing something?)
```
Starting BoomPow Client...
  ____                                ____     ___   __        __
 | __ )    ___     ___    _ __ ___   |  _ \   / _ \  \ \      / /
 |  _ \   / _ \   / _ \  | '_ ` _ \  | |_) | | | | |  \ \ /\ / /
 | |_) | | (_) | | (_) | | | | | | | |  __/  | |_| |   \ V  V /
 |____/   \___/   \___/  |_| |_| |_| |_|      \___/     \_/\_/


⚡ Using GPU 0
Platform: NVIDIA CUDA
Vendor: NVIDIA Corporation
Driver: 516.94

Only using GPU for work_generate...



🔒 Logging in...

🔓 Successfully logged in as *************


🚀 Initiating connection to BoomPOW...2022/08/15 21:25:33 websocket: bad handshake
2022/08/15 21:25:33 Dial: will try again in 2s seconds.
Websocket disconnected wss://boompow.banano.cc/ws/worker
```

GPU: Nvidia GeForce 3080
CPU: Intel I7 - 10875H
OS: Windows 11

**Comment by brainbudt** [comment]
Hey there,

There was a problem with the whole network. It's now back online.

**Comment by AquilesCrespo** [comment]
> Hey there,
> 
> There was a problem with the whole network. It's now back online.

I've tried again with no success ... still having the same output

**Comment by brainbudt** [comment]
Do you use a VPS on a datacenter?

**Comment by AquilesCrespo** [comment]
> Do you use a VPS on a datacenter?

This is the client on a Razer blade 17 with windows 11 as i stated above :)

**Comment by bbedward** [comment]
bad handshake is indicative of authentication failure, it may be because you haven't yet verified your email address

**Comment by AquilesCrespo** [comment]
> bad handshake is indicative of authentication failure, it may be because you haven't yet verified your email address

yeap... your right. thanks for the tip.
only one problem more the confirmation link is expired how can i request a new one?

**Comment by bbedward** [comment]
You can run `boompow-client.exe -resend-confirmation-email`

**Comment by AquilesCrespo** [comment]
> You can run `boompow-client.exe -resend-confirmation-email`

Thanks
